const fs = require('fs');
const path = require('path');

const htmlPath = path.join(__dirname, 'src', 'Edificios_sub.html');
const jsOutputPath = path.join(__dirname, 'src', 'assets', 'static', 'js', 'proveedores.js');

let htmlContent = fs.readFileSync(htmlPath, 'utf-8');

const selectStartTag = '<select id="selectProveedorElectricidad">';
const selectEndTag = '</select>';
const defaultOption = '<option value="">-- Selecciona un proveedor --</option>';

const selectStartIndex = htmlContent.indexOf(selectStartTag);
const selectEndIndex = htmlContent.indexOf(selectEndTag, selectStartIndex);

if (selectStartIndex === -1 || selectEndIndex === -1) {
    console.error("No se pudo encontrar el bloque de selectProveedorElectricidad.");
    process.exit(1);
}

const selectBlock = htmlContent.substring(selectStartIndex + selectStartTag.length, selectEndIndex);

const optionRegex = /<option\s+value="([^"]+)">([^<]+)<\/option>/g;
const proveedoresList = [];
let match;
const uniqueProveedores = new Set();

while ((match = optionRegex.exec(selectBlock)) !== null) {
    const value = match[1].trim();
    if (value && value !== '-- Selecciona un proveedor --') {
        uniqueProveedores.add(value);
    }
}

const proveedoresArray = Array.from(uniqueProveedores).sort();

const jsContent = `// generated by extract_options.js
const proveedoresElectricidad = ${JSON.stringify(proveedoresArray, null, 4)};

// If running in browser or module, export/expose appropriately
if (typeof module !== 'undefined' && module.exports) {
    module.exports = proveedoresElectricidad;
} else if (typeof window !== 'undefined') {
    window.proveedoresElectricidad = proveedoresElectricidad;
}
`;

fs.writeFileSync(jsOutputPath, jsContent, 'utf-8');
console.log(`Extracted ${proveedoresArray.length} unique providers to ${jsOutputPath}`);

// Rewrite HTML
const newHtmlContent = htmlContent.substring(0, selectStartIndex + selectStartTag.length) +
    `\n                                ${defaultOption}\n                                <!-- Las opciones se cargarán dinámicamente desde proveedores.js -->\n                            ` +
    htmlContent.substring(selectEndIndex);

fs.writeFileSync(htmlPath, newHtmlContent, 'utf-8');
console.log('Edificios_sub.html updated with dynamic options placeholder.');
